apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: projet-3k8s
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZS1kYXRhYmFzZQ==       
  POSTGRES_USER: dXNlcg==                     
  POSTGRES_PASSWORD: UEAzc3cwcmQ=             
